services:
  munin:
    image: dockurr/munin
    container_name: munin
    environment:
      TZ: "UTC"
      NODES: "server:10.0.0.101,nas:10.0.0.102"
    ports:
      - 80:80
    volumes:
      - ./lib:/var/lib/munin
      - ./log:/var/log/munin
      - ./conf:/etc/munin/munin-conf.d
      - ./plugin:/etc/munin/plugin-conf.d
    restart: always
    stop_grace_period: 1m
